import type { SoundDefinition } from './SoundBank';

export const SOUND_DEFINITIONS: SoundDefinition[] = [
  {
    id: 'player_jump',
    variations: ['/sounds/sfx/jump_01.wav', '/sounds/sfx/jump_02.wav', '/sounds/sfx/jump_03.wav'],
    volume: { min: 0.7, max: 0.85 },
    pitch: { min: 0.95, max: 1.05 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 50,
    minDistance: 5,
    cooldown: 100,
    priority: 5,
    maxInstances: 4,
  },
  {
    id: 'player_land',
    variations: ['/sounds/sfx/land_01.wav'],
    volume: { min: 0.1, max: 0.5 },
    pitch: { min: 0.9, max: 1.1 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 50,
    minDistance: 5,
    cooldown: 50,
    priority: 6,
    maxInstances: 4,
  },
  {
    id: 'player_footstep',
    variations: ['/sounds/sfx/footstep_01.wav', '/sounds/sfx/footstep_02.wav', '/sounds/sfx/footstep_03.wav', '/sounds/sfx/footstep_04.wav', '/sounds/sfx/footstep_05.wav' ],
    volume: { min: 0.1, max: 0.2 },
    pitch: { min: 0.8, max: 0.9 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 30,
    minDistance: 3,
    cooldown: 50,
    priority: 2,
    maxInstances: 5,
  },
  {
    id: 'ui_click',
    variations: ['/sounds/sfx/ui_click.mp3'],
    volume: { min: 0.2, max: 0.4 },
    pitch: { min: 0.9, max: 1.1 },
    bus: 'sfx',
    spatial: false,
    maxDistance: 30,
    minDistance: 3,
    cooldown: 50,
    priority: 2,
    maxInstances: 8,
  },
    {
    id: 'amb_forest',
    variations: ['/sounds/sfx/amb_forest.mp3'],
    volume: { min: 0.6, max: 0.8 },
    pitch: { min: 0.9, max: 1.1 },
    bus: 'ambient',
    spatial: false,
    maxDistance: 30,
    minDistance: 3,
    cooldown: 50,
    priority: 2,
    maxInstances: 1,
  },
];
