import type { SoundDefinition } from './SoundBank';

export const SOUND_DEFINITIONS: SoundDefinition[] = [
  // ─── Movement - Generic (fallback) ──────────────────────────────────────────
  {
    id: 'player_jump',
    variations: ['/sounds/sfx/mouvement/jump_01.wav', '/sounds/sfx/mouvement/jump_02.wav', '/sounds/sfx/mouvement/jump_03.wav', '/sounds/sfx/mouvement/jump_04.wav'],
    volume: { min: 3.5, max: 5.8 },
    pitch: { min: 0.95, max: 1.05 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 50,
    minDistance: 5,
    cooldown: 100,
    priority: 5,
    maxInstances: 4,
  },
  {
    id: 'player_land',
    variations: ['/sounds/sfx/mouvement/land_01.wav'],
    volume: { min: 0.5, max: 0.8 },
    pitch: { min: 0.9, max: 1.1 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 50,
    minDistance: 5,
    cooldown: 50,
    priority: 6,
    maxInstances: 4,
  },
  {
    id: 'player_footstep',
    variations: ['/sounds/sfx/mouvement/footstep_grass_01.wav', '/sounds/sfx/mouvement/footstep_grass_02.wav', '/sounds/sfx/mouvement/footstep_grass_03.wav', '/sounds/sfx/mouvement/footstep_grass_04.wav', '/sounds/sfx/mouvement/footstep_grass_05.wav'],
    volume: { min: 0.8, max: 1.2 },
    pitch: { min: 0.8, max: 0.9 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 30,
    minDistance: 3,
    cooldown: 50,
    priority: 2,
    maxInstances: 5,
  },

  // ─── Movement - Knight ──────────────────────────────────────────────────────
  {
    id: 'knight_footstep',
    variations: ['/sounds/sfx/mouvement/knight/knight_footstep_01.wav', '/sounds/sfx/mouvement/knight/knight_footstep_02.wav', '/sounds/sfx/mouvement/knight/knight_footstep_03.wav'],
    volume: { min: 1.0, max: 1.3 },
    pitch: { min: 0.85, max: 0.95 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 35,
    minDistance: 3,
    cooldown: 50,
    priority: 2,
    maxInstances: 5,
  },
  {
    id: 'knight_jump',
    variations: ['/sounds/sfx/mouvement/knight/knight_jump_01.wav', '/sounds/sfx/mouvement/knight/knight_jump_02.wav', '/sounds/sfx/mouvement/knight/knight_jump_03.wav'],
    volume: { min: 3.5, max: 5.8 },
    pitch: { min: 0.85, max: 0.95 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 50,
    minDistance: 5,
    cooldown: 100,
    priority: 5,
    maxInstances: 4,
  },
  {
    id: 'knight_land',
    variations: ['/sounds/sfx/mouvement/knight/knight_land_01.wav', '/sounds/sfx/mouvement/knight/knight_land_02.wav'],
    volume: { min: 3.0, max: 3.3 },
    pitch: { min: 0.8, max: 0.95 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 50,
    minDistance: 5,
    cooldown: 50,
    priority: 6,
    maxInstances: 4,
  },
  {
    id: 'knight_foley',
    variations: ['/sounds/sfx/mouvement/knight/knight_armor_foley_01.wav', '/sounds/sfx/mouvement/knight/knight_armor_foley_02.wav', '/sounds/sfx/mouvement/knight/knight_armor_foley_03.wav', '/sounds/sfx/mouvement/knight/knight_armor_foley_04.wav'],
    volume: { min: 0.3, max: 0.6 },
    pitch: { min: 0.9, max: 1.1 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 20,
    minDistance: 2,
    cooldown: 200,
    priority: 1,
    maxInstances: 3,
  },

  // ─── Movement - Rogue ───────────────────────────────────────────────────────
  {
    id: 'rogue_footstep',
    variations: ['/sounds/sfx/mouvement/rogue/rogue_footstep_01.wav', '/sounds/sfx/mouvement/rogue/rogue_footstep_02.wav', '/sounds/sfx/mouvement/rogue/rogue_footstep_03.wav'],
    volume: { min: 0.5, max: 0.8 },
    pitch: { min: 1.30, max: 1.50 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 20,
    minDistance: 2,
    cooldown: 50,
    priority: 2,
    maxInstances: 5,
  },
  {
    id: 'rogue_jump',
    variations: ['/sounds/sfx/mouvement/rogue/rogue_jump_01.wav', '/sounds/sfx/mouvement/rogue/rogue_jump_02.wav', '/sounds/sfx/mouvement/rogue/rogue_jump_03.wav'],
    volume: { min: 2.5, max: 4.0 },
    pitch: { min: 1.0, max: 1.15 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 40,
    minDistance: 4,
    cooldown: 100,
    priority: 5,
    maxInstances: 4,
  },
  {
    id: 'rogue_land',
    variations: ['/sounds/sfx/mouvement/rogue/rogue_land_01.wav', '/sounds/sfx/mouvement/rogue/rogue_land_02.wav'],
    volume: { min: 2.3, max: 2.5 },
    pitch: { min: 1.2, max: 1.35 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 30,
    minDistance: 3,
    cooldown: 50,
    priority: 6,
    maxInstances: 4,
  },
  {
    id: 'rogue_foley',
    variations: ['/sounds/sfx/mouvement/rogue/rogue_leather_foley_01.wav', '/sounds/sfx/mouvement/rogue/rogue_leather_foley_02.wav', '/sounds/sfx/mouvement/rogue/rogue_leather_foley_03.wav', '/sounds/sfx/mouvement/rogue/rogue_leather_foley_04.wav'],
    volume: { min: 0.2, max: 0.4 },
    pitch: { min: 0.95, max: 1.1 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 15,
    minDistance: 2,
    cooldown: 250,
    priority: 1,
    maxInstances: 3,
  },
  {
    id: 'ui_notif',
    variations: ['/sounds/ui/ui_notif.mp3'],
    volume: { min: 0.3, max: 0.3 },
    pitch: { min: 1, max: 1 },
    bus: 'ui',
    spatial: false,
    maxDistance: 1000,
    minDistance: 1,
    cooldown: 300,
    priority: 3,
    maxInstances: 3,
  },
  {
    id: 'ui_click',
    variations: ['/sounds/ui/ui_click.mp3'],
    volume: { min: 0.08, max: 0.08 },
    pitch: { min: 0.9, max: 1.1 },
    bus: 'sfx',
    spatial: false,
    maxDistance: 30,
    minDistance: 3,
    cooldown: 50,
    priority: 2,
    maxInstances: 8,
  },
  {
    id: 'player_attack_swing',
    variations: ['/sounds/sfx/swoosh_quick_01.wav', '/sounds/sfx/swoosh_quick_02.wav', '/sounds/sfx/swoosh_quick_03.wav', '/sounds/sfx/swoosh_quick_04.wav', '/sounds/sfx/swoosh_quick_05.wav'],
    volume: { min: 5.0, max: 7.0 },
    pitch: { min: 0.9, max: 1.1 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 20,
    minDistance: 2,
    cooldown: 300,
    priority: 4,
    maxInstances: 3,
  },
  {
    id: 'player_hit',
    variations: ['/sounds/sfx/player_hit_01.wav'],
    volume: { min: 1.0, max: 1.4 },
    pitch: { min: 0.95, max: 1.08 },
    bus: 'sfx',
    spatial: true,
    maxDistance: 40,
    minDistance: 3,
    cooldown: 50,
    priority: 7,
    maxInstances: 4,
  },
  {
    id: 'music_main_theme',
    variations: ['/sounds/music/music_main_theme_01.wav'],
    volume: { min: 0.4, max: 0.4 },
    pitch: { min: 1.0, max: 1.0 },
    bus: 'music',
    spatial: false,
    maxDistance: 1000,
    minDistance: 1,
    cooldown: 0,
    priority: 1,
    maxInstances: 1,
  },
  {
    id: 'music_dashboard',
    variations: ['/sounds/music/music_dashbord.mp3'],
    volume: { min: 0.35, max: 0.35 },
    pitch: { min: 1.0, max: 1.0 },
    bus: 'music',
    spatial: false,
    maxDistance: 1000,
    minDistance: 1,
    cooldown: 0,
    priority: 1,
    maxInstances: 1,
  },
  {
    id: 'amb_montagne',
    variations: ['/sounds/ambient/amb_montagne.wav'],
    volume: { min: 0.5, max: 0.5 },
    pitch: { min: 1.0, max: 1.0 },
    bus: 'ambient',
    spatial: false,
    maxDistance: 1000,
    minDistance: 1,
    cooldown: 0,
    priority: 2,
    maxInstances: 1,
  },
  {
    id: 'amb_forest',
    variations: ['/sounds/ambient/amb_forest.mp3'],
    volume: { min: 2.5, max: 4.2 },
    pitch: { min: 0.9, max: 1.1 },
    bus: 'ambient',
    spatial: false,
    maxDistance: 30,
    minDistance: 3,
    cooldown: 50,
    priority: 2,
    maxInstances: 1,
  },
];
