version: 2
updates:
  # Maintain dependencies for the Rust backend
  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  # Maintain dependencies for the Frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
