services:
  backend:
    image: ghcr.io/antonsplavnik/transcendence:latest
    # not using host network causes the ip address of
    # all incoming connections to be the same (the one of the docker bridge),
    # which breaks rate limiting and session ip identification
    network_mode: host
    user: "0:0"
    entrypoint: ["/app/transcendence-backend"]
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
    # ports:
    #   - "80:80"
    #   - "443:443/tcp"
    #   - "443:443/udp"
    volumes:
      - db-data:/app/data
      - acme-cache:/app/acme
      - ./prod_config.toml:/app/config.toml:ro
    env_file: .env
    restart: unless-stopped

  watchtower:
    image: nickfedor/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 300
      WATCHTOWER_CLEANUP: "true"
    restart: unless-stopped

volumes:
  db-data:
  acme-cache:
