services:
  transcendence:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8443:8443/udp"
    volumes:
      - db-data:/app/data
      - ./backend/certs:/app/certs
    env_file:
      - path: backend/.env
        required: false
volumes:
  db-data:
