CREATE TABLE user_stats (
	user_id INTEGER NOT NULL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
	xp INTEGER NOT NULL DEFAULT 0,
	level INTEGER NOT NULL DEFAULT 1,
	games_played INTEGER NOT NULL DEFAULT 0,
	games_won INTEGER NOT NULL DEFAULT 0,
	current_win_streak INTEGER NOT NULL DEFAULT 0,
	best_win_streak INTEGER NOT NULL DEFAULT 0,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
);
