ALTER TABLE user_stats ADD COLUMN kills INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN deaths INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN damage_dealt FLOAT NOT NULL DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN damage_taken FLOAT NOT NULL DEFAULT 0;
